# Generated by Django 3.1.3 on 2020-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201208_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='identificador'),
            preserve_default=False,
        ),
    ]
