# Generated by Django 3.1.3 on 2020-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201107_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(verbose_name='Sobre o Curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
    ]
