# Generated by Django 3.1.3 on 2020-12-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201123_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['number'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
    ]
